### ISSUE TITLE
 Unsupported types in alloca: Type=StructTyID

### ISSUE THREAD

**Issue by zaoqi** [maropu/lljvm-translator#11]
https://gitlab.com/the-language/the-language/blob/c661c4f3fc13026a80d57fef31cdcdd2422d7ba2/core/arch/c/lang.c
```
$ ./bin/lljvm-translator lang.bc 
/home/1828_sandbox/src/github.com-maropu-lljvm-translator/lljvm-translator-master/bin/../target/lljvm-core_0.3.0-EXPERIMENTAL-with-dependencies.jar not found, so use pre-compiled /home/1828_sandbox/src/github.com-maropu-lljvm-translator/lljvm-translator-master/bin/../assembly/lljvm-core_0.3.0-EXPERIMENTAL-with-dependencies.jar
io.github.maropu.lljvm.LLJVMRuntimeException: Unsupported types in alloca: Type=StructTyID
	at io.github.maropu.lljvm.LLJVMNative.throwException(LLJVMNative.java:65)
	at io.github.maropu.lljvm.LLJVMNative.asJVMAssemblyCode(Native Method)
	at io.github.maropu.lljvm.LLJVMTranslator.main(LLJVMTranslator.java:50)
```

**Comment by maropu** [comment]
This project doesn't target a full-fledge transformation, so I feel its difficult to support the conversion in the example above....
