### ISSUE TITLE
build fail of "error: scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found."

### ISSUE THREAD

**Issue by yansendao** [maropu/lljvm-translator#12]
```
[WARNING]  Expected all dependencies to require Scala version: 2.11.8
[WARNING]  io.github.maropu:lljvm-core:0.3.0-EXPERIMENTAL requires scala version: 2.11.8
[WARNING]  org.scalatest:scalatest_2.11:3.0.3 requires scala version: 2.11.8
[WARNING]  org.scalactic:scalactic_2.11:3.0.3 requires scala version: 2.11.8
[WARNING]  org.scala-lang:scala-reflect:2.11.8 requires scala version: 2.11.8
[WARNING]  org.scala-lang.modules:scala-xml_2.11:1.0.5 requires scala version: 2.11.7
[WARNING] Multiple versions of scala libraries detected!
[INFO] Using zinc server for incremental compilation
[info] 'compiler-interface' not yet compiled for Scala 2.11.8. Compiling...
error: scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
        at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:17)
        at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:18)
        at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:53)
        at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
        at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
        at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:66)
        at scala.reflect.internal.Mirrors$RootsBase.getClassByName(Mirrors.scala:102)
        at scala.reflect.internal.Mirrors$RootsBase.getRequiredClass(Mirrors.scala:105)
        at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass$lzycompute(Definitions.scala:257)
        at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass(Definitions.scala:257)
        at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1394)
        at scala.tools.nsc.Global$Run.<init>(Global.scala:1215)
        at scala.tools.nsc.Driver.doCompile(Driver.scala:31)
        at scala.tools.nsc.MainClass.doCompile(Main.scala:23)
        at scala.tools.nsc.Driver.process(Driver.scala:51)
        at scala.tools.nsc.Main.process(Main.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at sbt.compiler.RawCompiler.apply(RawCompiler.scala:33)
        at sbt.compiler.AnalyzingCompiler$$anonfun$compileSources$1$$anonfun$apply$2.apply(AnalyzingCompiler.scala:159)
        at sbt.compiler.AnalyzingCompiler$$anonfun$compileSources$1$$anonfun$apply$2.apply(AnalyzingCompiler.scala:155)
        at sbt.IO$.withTemporaryDirectory(IO.scala:358)
        at sbt.compiler.AnalyzingCompiler$$anonfun$compileSources$1.apply(AnalyzingCompiler.scala:155)
        at sbt.compiler.AnalyzingCompiler$$anonfun$compileSources$1.apply(AnalyzingCompiler.scala:152)
        at sbt.IO$.withTemporaryDirectory(IO.scala:358)
        at sbt.compiler.AnalyzingCompiler$.compileSources(AnalyzingCompiler.scala:152)
        at sbt.compiler.IC$.compileInterfaceJar(IncrementalCompiler.scala:58)
        at com.typesafe.zinc.Compiler$.compilerInterface(Compiler.scala:154)
        at com.typesafe.zinc.Compiler$.create(Compiler.scala:55)
        at com.typesafe.zinc.Compiler$$anonfun$apply$1.apply(Compiler.scala:42)
        at com.typesafe.zinc.Compiler$$anonfun$apply$1.apply(Compiler.scala:42)
        at com.typesafe.zinc.Cache.get(Cache.scala:41)
        at com.typesafe.zinc.Compiler$.apply(Compiler.scala:42)
        at com.typesafe.zinc.Main$.run(Main.scala:96)
        at com.typesafe.zinc.Nailgun$.zinc(Nailgun.scala:95)
        at com.typesafe.zinc.Nailgun$.nailMain(Nailgun.scala:84)
        at com.typesafe.zinc.Nailgun.nailMain(Nailgun.scala)
        at jdk.internal.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.martiansoftware.nailgun.NGSession.run(NGSession.java:280)
[error] Compile failed at Dec 9, 2019, 4:35:51 PM [0.668s]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] LLJVM Translator Parent POM ........................ SUCCESS [  0.704 s]
[INFO] LLJVM Core ......................................... FAILURE [  1.729 s]
[INFO] C Extension for LLJVM .............................. SKIPPED
[INFO] Python Extension for LLJVM ......................... SKIPPED
[INFO] LLJVM Benchmark .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.597 s
[INFO] Finished at: 2019-12-09T16:35:51+08:00
[INFO] Final Memory: 25M/1566M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile (scala-compile-first) on project lljvm-core: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile failed.: CompileFailed -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :lljvm-core
```

**Comment by maropu** [comment]
Thanks for the report. You hit this issue when calling `./build/mvn clean package -DskipTests`?

**Comment by yansendao** [comment]
> Thanks for the report. You hit this issue when calling `./build/mvn clean package -DskipTests`?

I Does not use the -DskipTests options, but after I try this option again, it compalint the same message.

**Comment by maropu** [comment]
You used `AdoptOpenJDK`? I tried to check it on my env (Oracle JDK) now and it passed.
