### ISSUE TITLE
build fail of "io.github.maropu.lljvm.LLJVMRuntimeException: Java array addressing is not supported in Unknown 64-bit Java Runtime (vendor=AdoptOpenJDK)"

### ISSUE THREAD

**Issue by yansendao** [maropu/lljvm-translator#13]
```
- boolean *** FAILED ***
  io.github.maropu.lljvm.LLJVMRuntimeException: Java array addressing is not supported in Unknown 64-bit Java Runtime (vendor=AdoptOpenJDK)
  at io.github.maropu.lljvm.util.ArrayUtils._addressOf(ArrayUtils.java:70)
  at io.github.maropu.lljvm.util.ArrayUtils.addressOf(ArrayUtils.java:92)
  at io.github.maropu.lljvm.ArrayUtilsSuite$$anonfun$1.apply$mcV$sp(ArrayUtilsSuite.scala:27)
  at io.github.maropu.lljvm.ArrayUtilsSuite$$anonfun$1.apply(ArrayUtilsSuite.scala:25)
  at io.github.maropu.lljvm.ArrayUtilsSuite$$anonfun$1.apply(ArrayUtilsSuite.scala:25)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
  ...
- byte *** FAILED ***
  io.github.maropu.lljvm.LLJVMRuntimeException: Java array addressing is not supported in Unknown 64-bit Java Runtime (vendor=AdoptOpenJDK)
  at io.github.maropu.lljvm.util.ArrayUtils._addressOf(ArrayUtils.java:70)
  at io.github.maropu.lljvm.util.ArrayUtils.addressOf(ArrayUtils.java:96)
  at io.github.maropu.lljvm.ArrayUtilsSuite$$anonfun$2.apply$mcV$sp(ArrayUtilsSuite.scala:35)
  at io.github.maropu.lljvm.ArrayUtilsSuite$$anonfun$2.apply(ArrayUtilsSuite.scala:33)
  at io.github.maropu.lljvm.ArrayUtilsSuite$$anonfun$2.apply(ArrayUtilsSuite.scala:33)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
  ...
- short *** FAILED ***
  io.github.maropu.lljvm.LLJVMRuntimeException: Java array addressing is not supported in Unknown 64-bit Java Runtime (vendor=AdoptOpenJDK)
  at io.github.maropu.lljvm.util.ArrayUtils._addressOf(ArrayUtils.java:70)
  at io.github.maropu.lljvm.util.ArrayUtils.addressOf(ArrayUtils.java:100)
  at io.github.maropu.lljvm.ArrayUtilsSuite$$anonfun$3.apply$mcV$sp(ArrayUtilsSuite.scala:43)
  at io.github.maropu.lljvm.ArrayUtilsSuite$$anonfun$3.apply(ArrayUtilsSuite.scala:41)
  at io.github.maropu.lljvm.ArrayUtilsSuite$$anonfun$3.apply(ArrayUtilsSuite.scala:41)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
  ...
- int *** FAILED ***
  io.github.maropu.lljvm.LLJVMRuntimeException: Java array addressing is not supported in Unknown 64-bit Java Runtime (vendor=AdoptOpenJDK)
  at io.github.maropu.lljvm.util.ArrayUtils._addressOf(ArrayUtils.java:70)
  at io.github.maropu.lljvm.util.ArrayUtils.addressOf(ArrayUtils.java:104)
  at io.github.maropu.lljvm.ArrayUtilsSuite$$anonfun$4.apply$mcV$sp(ArrayUtilsSuite.scala:51)
  at io.github.maropu.lljvm.ArrayUtilsSuite$$anonfun$4.apply(ArrayUtilsSuite.scala:49)
  at io.github.maropu.lljvm.ArrayUtilsSuite$$anonfun$4.apply(ArrayUtilsSuite.scala:49)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
  ...
- long *** FAILED ***
  io.github.maropu.lljvm.LLJVMRuntimeException: Java array addressing is not supported in Unknown 64-bit Java Runtime (vendor=AdoptOpenJDK)
  at io.github.maropu.lljvm.util.ArrayUtils._addressOf(ArrayUtils.java:70)
  at io.github.maropu.lljvm.util.ArrayUtils.addressOf(ArrayUtils.java:108)
  at io.github.maropu.lljvm.ArrayUtilsSuite$$anonfun$5.apply$mcV$sp(ArrayUtilsSuite.scala:59)
  at io.github.maropu.lljvm.ArrayUtilsSuite$$anonfun$5.apply(ArrayUtilsSuite.scala:57)
  at io.github.maropu.lljvm.ArrayUtilsSuite$$anonfun$5.apply(ArrayUtilsSuite.scala:57)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
  ...
- float *** FAILED ***
  io.github.maropu.lljvm.LLJVMRuntimeException: Java array addressing is not supported in Unknown 64-bit Java Runtime (vendor=AdoptOpenJDK)
  at io.github.maropu.lljvm.util.ArrayUtils._addressOf(ArrayUtils.java:70)
  at io.github.maropu.lljvm.util.ArrayUtils.addressOf(ArrayUtils.java:112)
  at io.github.maropu.lljvm.ArrayUtilsSuite$$anonfun$7.apply$mcV$sp(ArrayUtilsSuite.scala:67)
  at io.github.maropu.lljvm.ArrayUtilsSuite$$anonfun$7.apply(ArrayUtilsSuite.scala:65)
  at io.github.maropu.lljvm.ArrayUtilsSuite$$anonfun$7.apply(ArrayUtilsSuite.scala:65)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
  ...
- double *** FAILED ***
  io.github.maropu.lljvm.LLJVMRuntimeException: Java array addressing is not supported in Unknown 64-bit Java Runtime (vendor=AdoptOpenJDK)
  at io.github.maropu.lljvm.util.ArrayUtils._addressOf(ArrayUtils.java:70)
  at io.github.maropu.lljvm.util.ArrayUtils.addressOf(ArrayUtils.java:116)
  at io.github.maropu.lljvm.ArrayUtilsSuite$$anonfun$9.apply$mcV$sp(ArrayUtilsSuite.scala:75)
  at io.github.maropu.lljvm.ArrayUtilsSuite$$anonfun$9.apply(ArrayUtilsSuite.scala:73)
  at io.github.maropu.lljvm.ArrayUtilsSuite$$anonfun$9.apply(ArrayUtilsSuite.scala:73)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
  ...
Run completed in 3 seconds, 736 milliseconds.
Total number of tests run: 101
Suites: completed 13, aborted 0
Tests: succeeded 80, failed 21, canceled 0, ignored 3, pending 0
*** 21 TESTS FAILED ***
```

jdk version:
```
$ java -version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.232-b09, mixed mode)
```

**Comment by maropu** [comment]
Yea, that's an expected behaivour. The array is supported only on limited platforms.
