### ISSUE TITLE
io.github.maropu.lljvm.LLJVMRuntimeException: Package(GeneratedClass20180731HMKjwzxmew) not supported

### ISSUE THREAD

**Issue by yansendao** [maropu/lljvm-translator#14]
![image](https://user-images.githubusercontent.com/36258307/70436533-7eb62580-1ac4-11ea-8825-cdbb92469009.png)

message:
```
io.github.maropu.lljvm.LLJVMRuntimeException: Package(GeneratedClass20180731HMKjwzxmew) not supported
        at io.github.maropu.lljvm.util.analysis.SupportedMethodPackages.checkIfPackageSupported(SupportedMethodPackages.java:42)
        at io.github.maropu.lljvm.util.analysis.BytecodeVerifier$SupportedBytecodeChecker$1.visitMethodInsn(BytecodeVerifier.java:144)
        at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2211)
        at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1274)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:679)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
        at io.github.maropu.lljvm.util.analysis.BytecodeVerifier.checkIfBytecodeSupported(BytecodeVerifier.java:86)
        at io.github.maropu.lljvm.util.analysis.BytecodeVerifier.verify(BytecodeVerifier.java:44)
        at io.github.maropu.lljvm.util.JVMAssembler.doCompile(JVMAssembler.java:73)
        at io.github.maropu.lljvm.util.JVMAssembler.compile(JVMAssembler.java:47)
        at io.github.maropu.lljvm.LLJVMTranslator.main(LLJVMTranslator.java:61)
```

clang version:
```
$ ../clang+llvm-7.0.1-x86_64-linux-gnu-ubuntu-18.04/bin/clang --version
clang version 7.0.1 (tags/RELEASE_701/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/yansendao/opensource/llvm-all/lljvm-translator/../clang+llvm-7.0.1-x86_64-linux-gnu-ubuntu-18.04/bin
```

**Comment by yansendao** [comment]
I use oracleJDK 8u231 when the problem occur：
```
$ java -version
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)
```
